export default [
    {
        tagname:"Vue",
        sum:13,
        id:"1"
    },
    {
        tagname:"React",
        sum:13,
        id:"2"
    },
    {
        tagname:"Node",
        sum:13,
        id:"3"
    },
    {
        tagname:"Game",
        sum:13,
        id:"4"
    },
    {
        tagname:"Git",
        sum:13,
        id:"5"
    },
    {
        tagname:"Http",
        sum:13,
        id:"6"
    },
    {
        tagname:"面试",
        sum:13,
        id:"7"
    },
    {
        tagname:"Mongodb",
        sum:13,
        id:"8"
    }
]